//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avaliacao()
        {
            this.Avaliacao1 = new HashSet<Avaliacao>();
        }
    
        public int Id { get; set; }
        public int Id_Avaliador_Projeto { get; set; }
        public Nullable<int> Nota_Quadro_1 { get; set; }
        public Nullable<int> Nota_Quadro_2 { get; set; }
        public Nullable<int> Nota_Quadro_3 { get; set; }
        public Nullable<int> Nota_Quadro_4 { get; set; }
        public Nullable<int> Nota_Quadro_5 { get; set; }
        public Nullable<int> Nota_Quadro_6 { get; set; }
        public Nullable<int> Nota_Quadro_7 { get; set; }
        public Nullable<int> Nota_Quadro_8 { get; set; }
        public Nullable<int> Nota_Quadro_9 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avaliacao> Avaliacao1 { get; set; }
        public virtual Avaliacao Avaliacao2 { get; set; }
    }
}
