//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CanvasEntities2 : DbContext
    {
        public CanvasEntities2()
            : base("name=CanvasEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Aluno> Aluno { get; set; }
        public virtual DbSet<Aluno_Projeto> Aluno_Projeto { get; set; }
        public virtual DbSet<Avaliacao> Avaliacao { get; set; }
        public virtual DbSet<Avaliador_Externo> Avaliador_Externo { get; set; }
        public virtual DbSet<Avaliador_Projeto> Avaliador_Projeto { get; set; }
        public virtual DbSet<Comentario> Comentario { get; set; }
        public virtual DbSet<Lideranca> Lideranca { get; set; }
        public virtual DbSet<Orientador_Projeto> Orientador_Projeto { get; set; }
        public virtual DbSet<Participante> Participante { get; set; }
        public virtual DbSet<Peso> Peso { get; set; }
        public virtual DbSet<Professor> Professor { get; set; }
        public virtual DbSet<Projeto> Projeto { get; set; }
    }
}
