//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int Id { get; set; }
        public int Id_Aluno_Projeto { get; set; }
        public string Quadro_1 { get; set; }
        public string Quadro_2 { get; set; }
        public string Quadro_3 { get; set; }
        public string Quadro_4 { get; set; }
        public string Quadro_5 { get; set; }
        public string Quadro_6 { get; set; }
        public string Quadro_7 { get; set; }
        public string Quadro_8 { get; set; }
        public string Quadro_9 { get; set; }
    
        public virtual Aluno_Projeto Aluno_Projeto { get; set; }
    }
}
