//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peso
    {
        public int Id { get; set; }
        public int Id_Projeto { get; set; }
        public Nullable<int> Peso_Quadro_1 { get; set; }
        public Nullable<int> Peso_Quadro_2 { get; set; }
        public Nullable<int> Peso_Quadro_3 { get; set; }
        public Nullable<int> Peso_Quadro_4 { get; set; }
        public Nullable<int> Peso_Quadro_5 { get; set; }
        public Nullable<int> Peso_Quadro_6 { get; set; }
        public Nullable<int> Peso_Quadro_7 { get; set; }
        public Nullable<int> Peso_Quadro_8 { get; set; }
        public Nullable<int> Peso_Quadro_9 { get; set; }
    
        public virtual Projeto Projeto { get; set; }
    }
}
